### ISSUE TITLE
Can you update package pls for new INTL 

### ISSUE THREAD

**Issue by Hellomik2002** [zathras/misc#3]
<img width="900" alt="Screenshot 2023-02-08 at 8 46 43 AM" src="https://user-images.githubusercontent.com/30003495/217415818-b45f8e03-28a9-4d15-8c93-79204f5dee78.png">

**Comment by zathras** [comment]
Done - published to dart.dev.  Thanks!  BTW, jovial_misc wasn't even using intl, so I just eliminated it.
